spring:
  application:
    name: ${SPRING_APP_NAME:template-backend-front}

server:
  port: ${SPRING_SERVER_PORT:9090}
  servlet:
    context-path: ${CONTEXT_PATH:/backend}
  error:
    include-message: always

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

management:
  endpoint:
    health:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
        ignore-exception-predicate: com.iep.mycompany.app.exception.CircuitBreakerIgnoreException


#configuracion de recurso que consume la aplicacion
company-test:
  uri: ${RESOURCE_COMPANY_TEST_URI:http://localhost:8080}